### PR TITLE
* Add support for views

### PR DESCRIPTION
**Pull request by ag-ramachandran**
* Add support for Views/Functions apart from Materialized views
* Facilitate local development adding support for AZ CLI based auth
* Upgrade Kusto libraries to latest version

### CODE REVIEW

**Comment by martingrin** [comment]
@ag-ramachandran hey! We'll see in about a week

**Comment by pa1ch** [comment]
@ag-ramachandran hi! Thank you for your PR. Could you add some unit tests for the new functionality?

**Comment by ag-ramachandran** [comment]
> @ag-ramachandran hi! Thank you for your PR. Could you add some unit tests for the new functionality?

Hello @pa1ch , done. Added tests for both the AZCLI based auth scenarios and also for the views addition.

**Review by pa1ch — APPROVED** [review]

**Comment by ag-ramachandran** [comment]
> @ag-ramachandran fix pylint errors please.
> 
> ```
> ************* Module sqlalchemy_kusto.dialect_base
> sqlalchemy_kusto/dialect_base.py:142:8: C0103: Variable name "mv" doesn't conform to snake_case naming style (invalid-name)
> ```

Hello @pa1ch , Fixed the formatting lint. Would you know why this fails


```
4. Run mypy for type checking.
.venv/bin/python -m mypy .
.venv/lib/python3.8/site-packages/_pytest/python.py:918: error: f-string: self documenting expressions are only supported in Python 3.8 and greater  [syntax]
Found 1 error in 1 file (errors prevented further checking)
make: *** [Makefile:39: check] Error 2
Error: Process completed with exit code 2.
```

**Comment by pa1ch** [comment]
@ag-ramachandran thank you for fix. I just fixed mypy error. Merge our master to your, please

**Review by pa1ch — APPROVED** [review]

**Pull request merged**
