### PR TITLE
[KQL] Add support for "schema" (used in cross-database joins)

### PR DESCRIPTION
**Pull request by Ceridan**
Add schema support for the KQL dialect.

Related issue: #7

### CODE REVIEW

**Comment by Ceridan** [comment]
According to [naming rules](https://docs.microsoft.com/en-us/azure/data-explorer/kusto/query/schema-entities/entity-names#identifier-naming-rules) the identifiers may contain "." (dots). In this case, my code wouldn't work. But actually, we can do nothing with naming that contains schema and name with dots. Let consider this situation as a very rare one.

**Comment by xneg** [comment]
According to naming rules
> Identifiers containing at least one of (spaces, dots, or dashes) do require quoting (see below).
Can we use quotes to avoid a situation with schema and name containing dots?

**Comment by xneg** [comment]
According to naming rules
> Identifiers containing at least one of (spaces, dots, or dashes) do require quoting (see below).
   
 Can we use quotes to avoid a situation with schema and name containing dots?

**Review by xneg — CHANGES_REQUESTED** [review]
According to naming rules

> Identifiers containing at least one of (spaces, dots, or dashes) do require quoting (see below).

Can we use quotes to avoid a situation with schema and name containing dots?

**Comment by Ceridan** [comment]
@xneg, I think the problem occurs when we extract a query from the text (see the `test_schema_from_query test`). What if we have the query like this: `mydb.my.table`. We can do nothing in this case.
Could you explain your idea in more detail?

**Comment by xneg** [comment]
`mydb.my.table` is not valid even in Kusto naming rules.
According to rules, this should look like `mydb."my.table"` and we can use this in our determination.

**Comment by Ceridan** [comment]
Oh, that's a good point, I will add such a test and fix the code. Thank you!

**Review by xneg — CHANGES_REQUESTED** [review]
I think there could be several cases:
database.table
database."table.name"
"table.name"
"database.name"."table.name"
"database.name".table

Your solution considers only 3 first. I think we need support for the last 2.

**Comment by Ceridan** [comment]
You are right. It makes checks more complicated, but actually, you are right :)
Additionally, I think we should switch to parametrized tests here, it will be more readable.
I will fix this.

**Comment by xneg** [comment]
Yes. I think parametrized tests would be great here. And I think the final code would be not very complicated but maybe recursive. :)

**Comment by Ceridan** [comment]
Or... Regular Expressions! :)

**Comment by xneg** [comment]
Yep! This is great!

**Review by xneg — APPROVED** [review]

**Pull request merged**
